---
title: 'Data Wrangling 1: Tidy Data'
author: "Derek Lamb"
date: "`r Sys.Date()`"
output: github_document
---

Load all necessary packages.
```{r load pacakges, message = FALSE}
library(tidyverse)
library(haven)
```

## PULSE data

```{r import data}
# Load and convert from wide to long format
pulse_df <- read_sas("data/public_pulse_data.sas7bdat") |> 
  janitor::clean_names() |> 
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "time",
    values_to = "bdi_score",
    names_prefix = "bdi_score_"
  ) |> 
  
# Recode baseline to 0 months
  mutate(
    time = replace(time, time == "bl", "00m")
  )
  
pulse_df
```

We observe that the BDI is long not wide and so used `pivot_longer` to make it long.

### Learning Assessment

```{r la litters}
litters_df <- read_csv("data/FAS_litters.csv") |> 
  janitor::clean_names() |>
  select(litter_number, gd0_weight, gd18_weight) |> 
  pivot_longer(
    gd0_weight:gd18_weight,
    names_to = "gd",
    values_to = "weight"
               ) |> 
  mutate(
    gd = case_match(
      gd,
      "gd0_weight" ~ 0,
      "gd18_weight" ~ 18
    )
  )
  
  
#litters_df
```

## LotR

Import LotR words data.

```{r import lotr data}
fellowship_df <- 
  readxl::read_excel(
    "data/LotR_Words.xlsx", 
    range = "B3:D6") |> 
  mutate(movie = "fellowship")

two_towers_df <- 
  readxl::read_excel(
    "data/LotR_Words.xlsx", 
    range = "F3:H6") |> 
  mutate(movie = "two_towers")

rotk_df <- 
  readxl::read_excel(
    "data/LotR_Words.xlsx", 
    range = "J3:L6") |> 
  mutate(movie = "rotk")

lotr_df <- bind_rows(fellowship_df, two_towers_df, rotk_df) |> 
  janitor::clean_names() |> 
  pivot_longer(
    female:male,
    names_to = "gender",
    values_to = "word_count"
               ) |> 
  mutate(race = str_to_lower(race)) |> 
  relocate(movie)
```

## Revisit FAS

```{r }
litters_df <- 
  read_csv("data/FAS_litters.csv") |> 
  janitor::clean_names() |> 
  mutate(wt_gain = gd18_weight - gd0_weight) |> 
  select(litter_number, group, wt_gain) |> 
  separate(group, into = c("dose","day_of_tx"), 3) |> 
  mutate(dose = str_to_lower(dose))

litters_df
```

Now pups
```{r}
pups_df <- read_csv("data/FAS_pups.csv") |> 
  janitor::clean_names() |> 
  mutate(
    sex = case_match(
      sex,
      1 ~ "male",
      2 ~ "female"
    )
  )

pups_df
```

Now join the two

```{r}
fas_df = left_join(pups_df, litters_df, by = "litter_number")

fas_df
```

