---
title: "Data Manipulation"
author: "Derek Lamb"
date: "`r Sys.Date()`"
output: github_document
---

First, load all necessary packages.
```{r load packages, message = FALSE}
library(tidyverse)
```

Import FAS litters and pups.
```{r import, message = 0}
# FAS Litters
litters_df =
  read_csv("data/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)

#FAS Pups
pups_df = 
  read_csv("data/FAS_pups.csv")
pups_df = janitor::clean_names(pups_df)
```

## `select`

`select` is used to select columns!
```{r select, message = FALSE}
# basic
select(litters_df, gd0_weight, group)

# colon selects range
select(litters_df, group, gd0_weight:gd_of_birth)

# starts_with
select(litters_df, group, starts_with("pups")) # also ends_with, contains

# remove columns
select(litters_df, -litter_number)
select(litters_df, -starts_with("gd"))

# rename variables
select(litters_df, group, litter_id = litter_number)

# everything()
select(litters_df, group, litter_id = litter_number, everything())
select(litters_df, gd0_weight, everything())

```

#### `select` vs `pull`
`select` outputs a dataframe, whereas `pull` creates a vector.
```{r select v pull, message = FALSE}
select(litters_df, group)

pull(litters_df, group)
```

## Learning Assessment

```{r learning assessment - select, message = FALSE}

select(pups_df, litter_number, sex, pd_ears)

```

## `filter`

Get rid of rows using `filter.
```{r filter}
# basic boolean logic
filter(litters_df, group == "Con7")
filter(litters_df, group != "Con7")
filter(litters_df, gd0_weight <= 20)

# or is "|"
filter(litters_df, group == "Con7" | group == "Con8")
filter(litters_df, group %in% c("Con7", "Con8"))

# negation
filter(litters_df, !(group == "Con7"))
```


### Missing data

``` {r missing data}
# remove all columns with missing values
drop_na(litters_df)

# one column
drop_na(litters_df, gd0_weight)

```

#### Learning Assessment

```{r}
filter(pups_df, sex == 1)
```



## `mutate`

```{r mutation}

mutate(litters_df, wt_gain = gd18_weight - gd0_weight)

# convert variable to lowercase
mutate(litters_df, group = str_to_lower(group))

mutate(
  litters_df,
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower(group)
)
```

## `arrange`

`arrange` sorts rows. It isn't useful for analyses, but is good for EDA.

```{r}
# one variable, sorting rows
arrange(litters_df, gd0_weight)

# two variables, in sequence
arrange(litters_df, group, gd0_weight)
```


# Pipes

```{r}
litters_df = 
  read_csv("data/FAS_litters.csv") |> 
  janitor::clean_names() |> 
  select(-starts_with("pups")) |> 
  mutate(
    group = str_to_lower(group),
    wt_gain = gd18_weight - gd0_weight
  ) |> 
  drop_na(wt_gain) |> 
  arrange(group, wt_gain) 

view(litters_df)
  
```

